from __future__ import annotations

from typing import Literal
from pydantic import BaseModel, Field

# ============================================================================
# Type Aliases
# ============================================================================

Continent = Literal[
    "Europe", "Asia", "North America", "South America", "Africa", "Oceania", "Antarctica"
]
BusinessRegion = Literal["AMER", "EMEA", "APAC", "LATAM"]


# ============================================================================
# Geo Models
# ============================================================================

class GeoCoordinates(BaseModel):
    """Geographic coordinates (latitude/longitude)."""
    lat: float
    lng: float


class GeoViewport(BaseModel):
    """Geographic viewport bounds (northeast/southwest corners)."""
    northeast: GeoCoordinates
    southwest: GeoCoordinates


class GeoRectangle(BaseModel):
    """Geographic rectangle for Google Places API (low/high corners)."""
    low: dict[str, float]  # {latitude, longitude}
    high: dict[str, float]  # {latitude, longitude}


class GeoData(BaseModel):
    """Complete geo metadata for a location."""
    lat: float
    lng: float
    viewport: GeoViewport
    rectangle: GeoRectangle


# ============================================================================
# Location Models
# ============================================================================

class ResolvedLocation(BaseModel):
    """
    Resolved location with full geo metadata.
    
    This model is NEVER generated by LLM - it's created deterministically
    by the geo resolution layer after LLM processing.
    """
    city: str | None = None
    state: str | None = None
    country: str | None = Field(default=None, description="ISO 3166-1 alpha-2 (e.g., DE, IN, US)")
    country_name: str | None = Field(default=None, description="Human-readable country name in English (e.g., Germany)")
    continent: Continent | None = None
    region: BusinessRegion | None = None
    geo: GeoData | None = Field(default=None, description="Geographic metadata (coordinates, viewport, rectangle)")


# ============================================================================
# Prompt Interpretation Model
# ============================================================================

class PromptInterpretation(BaseModel):
    """
    Structured interpretation of a user's search prompt.
    
    Fields are divided into:
    1. Metadata fields (set by post-processing, excluded from LLM)
    2. LLM-generated fields (normalized prompt, keywords, locations)
    3. Deterministically-resolved fields (set after LLM processing)
    """
    
    # ------------------------------------------------------------------------
    # Metadata fields (set by post-processing, not LLM)
    # ------------------------------------------------------------------------
    request_id: str = Field(default="", json_schema_extra={"llm_exclude": True})
    raw_prompt: str = Field(default="", json_schema_extra={"llm_exclude": True})
    matched_industries: list[str] | None = Field(default=None, json_schema_extra={"llm_exclude": True})
    
    # ------------------------------------------------------------------------
    # Deterministically-resolved fields (set after LLM processing)
    # ------------------------------------------------------------------------
    resolved_locations: list[ResolvedLocation] | None = Field(
        default=None,
        json_schema_extra={"llm_exclude": True},
        description="Deterministically resolved locations with full geo metadata. NEVER generated by LLM."
    )
    
    # ------------------------------------------------------------------------
    # LLM-generated fields
    # ------------------------------------------------------------------------
    normalized_prompt: str
    language: str
    normalized_prompt_en: str
    prompt_target: str

    prompt_keywords: list[str] | None = Field(default=None, json_schema_extra={"vote": "union"})
    places_text_queries: list[str] | None = Field(default=None, json_schema_extra={"vote": "union"})
    prompt_location: list[str] | None = Field(
        default=None,
        description="Raw location tokens extracted by LLM (e.g., ['Berlin', 'Germany']). Resolved deterministically later."
    )
    global_search: bool = Field(
        default=False,
        description="True if user expressed global intent (near me, worldwide, etc.)"
    )
