"""
Email Generator Configuration Module.

This module stores constants and configuration values for the email content
generation system. All configuration is centralized here for easy maintenance.

Configuration Categories:
- Email Templates: Subject lines and content templates
- Organization Details: Series name and organization info
- Worker Settings: Batch sizes and polling intervals
"""

from __future__ import annotations

# ============================================================================
# EMAIL TEMPLATE CONFIGURATION
# ============================================================================

# Default subject line for all generated emails
# This is a constant and will not be generated by LLM
DEFAULT_SUBJECT = "Invitation to Share Your Founder Story – Gründerstories"

# ============================================================================
# ORGANIZATION DETAILS
# ============================================================================

# Name of the story series/campaign
SERIES_NAME = "Gründerstories"

# Organization name conducting the campaign
ORGANISATION = "AFS Akademie"

# ============================================================================
# WORKER CONFIGURATION
# ============================================================================

# Number of rows to process in each batch
# Balances throughput with transaction size
BATCH_SIZE = 50

# Time to wait between polling cycles (in seconds)
# Prevents excessive database load while maintaining responsiveness
POLL_INTERVAL_SECONDS = 10